### ISSUE TITLE
None of the drivers for nvidia will boot to graphics or even give me terminal with 3080ti for popos.  

### ISSUE THREAD

**Issue by badrock21** [pop-os/nvidia-graphics-drivers#107]

**Comment by leviport** [comment]
Support for the 3080Ti was added in NVIDIA driver 460.84. Version 465.31 is on the way very soon: https://github.com/pop-os/nvidia-graphics-drivers/pull/106

Once it is available, you'll probably be able to boot with the `nomodeset` kernel parameter and update to the latest driver.
