### ISSUE TITLE
Steam GUI doesn't show, and process uses 100% CPU

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/nvidia-graphics-drivers#123]
**Issue**
Steam will update, then never launch the login GUI after a fresh install of Pop!_OS. The `steam` process will get stuck and use 100% CPU. I have waited 20+ minutes for the GUI to show, but it never does.

**Steps to Reproduce**
1. Fresh install of pop nvidia (21.04 or 21.10 or 20.04)
2. Run `sudo apt update && sudo apt upgrade -y && sudo reboot` do not touch the system until after the reboot.
3. Install steam via pop shop.
4. Launch steam via launcher.
5. Wait for steam update window to finish and close.
The login GUI will never show, and the `steam` process will be using 100% CPU.

**Notes**
 * Only on machines with switchable graphics
 * Only when machine is in hybrid mode. Switching to Nvidia graphics will resolve the issue
 * Rebooting the system again will resolve the issue permanently. The issue only seems to happen if following these fairly strict steps.

**Comment by leviport** [comment]
I haven't seen this lately, so I'm going to close it. I can reopen it if I'm mistaken.

**Comment by jarettmillard** [comment]
@leviport I had this happen in my new Oryx Pro 3 weeks ago when I first installed Steam.

**Comment by leviport** [comment]
Just once, or does it still happen on 510, which was released last week?

**Comment by jarettmillard** [comment]
Hybrid graphics were so unstable that I switched over to only using Nvidia after a few days. I haven't tried hybrid graphics on 510 yet, but I will try to remember to report back after I do.

**Comment by leviport** [comment]
Related to https://github.com/pop-os/nvidia-graphics-drivers/issues/61 do you think?

**Comment by jarettmillard** [comment]
No, this was without an external display attached. In addition to Steam never opening on first launch, on subsequent launches I would get full-system freezes in hybrid mode within a few minutes if I opened Steam. I couldn't even switch to a tty and log in.

**Comment by leviport** [comment]
Gotcha, thanks for the info

**Comment by jarettmillard** [comment]
I tried switching back to hybrid graphics today and I haven't had any lock ups yet. It's hard to say what fixed it, but 510 is a likely suspect. Unfortunately, I'm not sure if my stability issues were related to the original problem with Steam or not, since that specific problem only happened on the initial run of Steam.

**Comment by leviport** [comment]
Think it's ok to close the issue now?

**Comment by jarettmillard** [comment]
Maybe? I guess it can always be reopened if someone experiences the original issue running 510.
