### ISSUE TITLE
cant update my nvidia drivers

### ISSUE THREAD

**Issue by gil938271** [pop-os/nvidia-graphics-drivers#141]
i tried to do a sudo apt update upgrade and it didn't work what should i do
![Screenshot from 2022-02-25 14-03-23](https://user-images.githubusercontent.com/84280265/155712347-b45746e1-35ad-425a-ad95-5cdb06701edb.png)
?

**Comment by leviport** [comment]
Looks like the 470 transitional packaging is still installed. Try `sudo apt remove '*nvidia*470*'` and then upgrade.

**Comment by JakXLT** [comment]
> Looks like the 470 transitional packaging is still installed. Try `sudo apt remove '*nvidia*470*'` and then upgrade.

I have the exact same issue and log. That did the trick. Tyvm, I'm far too green with linux to have fixed this myself X_X
