### ISSUE TITLE
Issue with GUI after computer wakes from sleep

### ISSUE THREAD

**Issue by superbazzooka** [pop-os/nvidia-graphics-drivers#169]
**Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 22.04 LTS
64-bit
GNOME version 42.4
windowing system x11

**Issue/Bug Description:**

This has only happened once, usually all is good. After waking my PC from sleep the GUI is all bugged out. Usually STEAM is the only program which suffers from this issue, but this one time, it happened with the system GUI (see screenshots), Opening the console with alt+F2 and running 'r' solved the issue.

![Bugged UI after sleep 3](https://user-images.githubusercontent.com/117637121/200356373-94a311a4-a1ab-4444-b2a4-1c5a1147e91b.png)
 
![Bugged UI after sleep 4](https://user-images.githubusercontent.com/117637121/200357384-5b3f01b5-9bed-47ea-8508-87a28e2eaf04.png)

![Bugged UI after sleep 1](https://user-images.githubusercontent.com/117637121/200356160-c8f56dfb-3b11-431a-af75-0e13f8d6cd40.png)

**Steps to reproduce (if you know):**

I am not able to reproduce the bug, it happened once in 2 months.

**Other Notes:**

GPU : Nvidia GTX 1070
CPU : 9900k
32GB RAM
NVME

**Comment by superbazzooka** [comment]
> I'm not seeing any screenshots here. Are you seeing text corruption like what is shown in this issue #133?

Hello, yes it seems that the issue is very similar, although the graphical bug seems to be slightly different. Also the bug doesn't happen 60% of the time but almost never, Steam so far seems to be the only application where this problem happens always and consistently.

**Comment by n3m0-22** [comment]
I would check the NVIDIA driver version you are using. You can do this by running the command `nvidia-smi`. If the driver version is not `515` you can update it by running the following:

```
sudo apt purge ~nnvida
sudo apt autoremove && sudo apt clean
sudo apt install nvidia-driver-515
```

If that does not fix it you can try running the same commands substituting `470` for `515` to see if the older driver helps.

Finally you can also try changing the graphics mode. If it is not already change it from NVIDIA to Hybrid.

**Comment by raneameya** [comment]
I am also facing the same issue. My drivers are the latest `515` (not the open one). Logging out and logging back in solves it
