### ISSUE TITLE
Plymouth does not display on NVIDIA RTX 4080

### ISSUE THREAD

**Issue by jacobktm** [pop-os/nvidia-graphics-drivers#175]
With an encrypted install of Pop! OS 22.04 plymouth does not display at startup with an NVIDIA RTX 4080 installed. At boot I only get a blank screen. If I type the password to decrypt the system at that blank screen it does work and I do get the Pop! OS login screen.

**Comment by leviport** [comment]
I believe this was fixed? We can reopen if I'm mistaken.
