### ISSUE TITLE
cuda_diagnostics.cc:308] kernel version 418.56.0 does not match DSO version 430.34.0 -- cannot find working devices in this configuration

### ISSUE THREAD

**Issue by phobrain** [pop-os/nvidia-graphics-drivers#18]
I just did an update and tried to run tensorflow.keras, but got the title error.

Next to figure how to roll it back.

**Comment by mmstick** [comment]
Did you reboot after installing the updated driver?

**Comment by phobrain** [comment]
Bingo! I had just rebooted before the update, and somehow assumed all was fresh in spite of having updated.

physical GPU (device: 0, name: GeForce RTX 2070,
