### ISSUE TITLE
Pop!_Shop showing install button for old driver version under Updates & Installed Software

### ISSUE THREAD

**Issue by sampellino** [pop-os/nvidia-graphics-drivers#198]
![image](https://github.com/pop-os/nvidia-graphics-drivers/assets/5458241/85e9e580-e493-47f5-89bd-934dee51abbd)

I have the 545.29.06 NVIDIA drivers installed, but the pop shop is wanting me to install the 470.199.02 driver. There is no way to remove it from the Updates & Installed Software menu.

Version info:
![image](https://github.com/pop-os/nvidia-graphics-drivers/assets/5458241/779160f3-0e4a-40c0-9946-13d632cf1253)

**Comment by mmstick** [comment]
Not a bug. This lists all supported drivers.

**Comment by sampellino** [comment]
If that's true, why is it not showing all supported older drivers to choose from? Why only one specific older version?

**Comment by mmstick** [comment]
These are the only drivers that we've packaged which remain in the repositories.

**Comment by sampellino** [comment]
Ahh, makes sense. Closing issue.
