### ISSUE TITLE
Test and release NVIDIA 418.56

### ISSUE THREAD

**Issue by brs17** [pop-os/nvidia-graphics-drivers#2]

**Comment by brs17** [comment]
Pop!_OS looks good, still trying to figure out 418 in Ubuntu 18.04.

**Comment by mmstick** [comment]
Still stumped on that. Ubuntu Software Updater will upgrade to the 418.56 driver, but `apt upgrade` will not. `aptitude upgrade` and `apt full-upgrade` work, of course.

**Comment by brs17** [comment]
@mmstick collaborate your efforts with @jackpot51 , I know he's been working on it as well

**Comment by jackpot51** [comment]
We released it
