### ISSUE TITLE
Will v550 beta be tested in the staging branch?

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/nvidia-graphics-drivers#200]
It should be useful to test this using staging branch, to see if issues with COSMIC are fixed or not (and if the damn stuttering if a game is under 60FPS is finally corrected or not).

**Comment by mmstick** [comment]
All branches on GitHub are automatically built in a staging branch with the same name. So yes.

**Comment by gabriele2000** [comment]
Nice!

**Comment by gabriele2000** [comment]
> All branches on GitHub are automatically built in a staging branch with the same name. So yes.

Nice!
