### ISSUE TITLE
system76-driver-nvidia installs both version 435 and 440

### ISSUE THREAD

**Issue by hugglesfox** [pop-os/nvidia-graphics-drivers#37]
The `system76-driver-nvidia` package depends on both `nvidia-driver-440` and `nvidia-driver-435` which is creating this situation where both the drivers are installed and thus instability can occur.

_Originally posted by @haydenhughes in https://github.com/pop-os/nvidia-graphics-drivers/issues/32#issuecomment-564921791_

**Comment by mmstick** [comment]
This is fine, because the 435 driver is just a metapackage that points to 440. Instability therefore cannot occur.
