### ISSUE TITLE
How to install latest 440.64 drivers?

### ISSUE THREAD

**Issue by acrovia** [pop-os/nvidia-graphics-drivers#45]
Hello,
I love pop-os because of it's stability, but dudes, we all want to play latest games with Vulkan. Specially now in quarantine. 
Can you upgrade it faster ?
Or can you give a solution on how to purge the pop-os drivers an use the latest ones? Will that destroy my system?
Thanks!

**Comment by chuckyz** [comment]
440.64 is already out with 440.82 in PR.  just `sudo apt-get upgrade nvidia-driver-440` should do the trick.  I believe this is also possible through the pop shop but I'm not sure what the right package is.

**Comment by Vyrr** [comment]
IIRC Nvidia driver number does not make sense and beta drivers are not following the same notation as public drivers.
See here: https://developer.nvidia.com/vulkan-driver
Can confirm that driver 440.82 does not support Vulkan 1.2, and beta driver 440.66 (as of today) does support Vulkan 1.2.

**Comment by thierrydev** [comment]
I have to say that it seems to be a bit of a struggle to install or update  Vulkan Beta Driver

**Comment by thierrydev** [comment]
this feature  seem to be ignored by design to favor[ System76 products ](https://support.system76.com/articles/system76-driver/)

**Comment by jacobgkau** [comment]
We are currently shipping NVIDIA driver version 440.100.
