### ISSUE TITLE
Time schedule for driver 450.x

### ISSUE THREAD

**Issue by rabbull** [pop-os/nvidia-graphics-drivers#55]
Hi,

I'm expecting to use the latest 450.x driver on my Pop! OS, but obviously it's not in the package manager currently. Seems that there is already a branch and a pull request for 450.x release. Have it been released as a preview version or something? If not, when approximately would a release for 450.x driver be published? Thanks in advance.

Regards,

**Comment by mmstick** [comment]
When NVIDIA releases a version of 450.XX that doesn't cause bugs in Mutter, it will be released. The current driver release causes regressions.
