### ISSUE TITLE
The current Nvidia driver 455.23 breaks some games with Proton

### ISSUE THREAD

**Issue by zelfir** [pop-os/nvidia-graphics-drivers#62]
Running Pop_OS 20.04 from an optimus enabled laptop with RTX 2060.
For example, The Elder Scrolls Online from Steam is now freezing on the connection screen since I upgraded from the 440.100 to the proposed 455.23.
I'm pretty sure it's the driver because using the latest stable from Nvidia (450.80.02) seems to fix the issue.
Is there a way to rollback to the 440.100 until you propose the 450.80.02 from your repo ?

**Comment by mmstick** [comment]
Does `nvidia-smi` report 455.23?

**Comment by zelfir** [comment]
Yep, 455.23.04 to be exact.

**Comment by Redbatman89** [comment]
If you have timeshift then use that to roll back. 455.23.04 was giving me issues too with vulkan shaders taking so long to process.

**Comment by jacobgkau** [comment]
455.28 has been released. @leviport found that it reduced Vulkan shader processing time. The NVIDIA changelog also indicates that some bugs with Vulkan applications (including a Steam Play title) were fixed.

@zelfir @Redbatman89 Can you check if you're still experiencing issues after upgrading to 455.28 and rebooting?

**Comment by zelfir** [comment]
I can't update actually because http://ppa.launchpad.net/wireguard/wireguard/ubuntu Focal Release is missing the Release file :/

**Comment by jacobgkau** [comment]
> I can't update actually because http://ppa.launchpad.net/wireguard/wireguard/ubuntu Focal Release is missing the Release file :/

That does not sound related to this issue, and that PPA is not a default repository included in Pop. Furthermore, it looks like that PPA has been decommissioned: https://launchpad.net/~wireguard 

You can remove it by editing your `/etc/sources.list` or `/etc/sources.list.d` files, or by using the GUI in Repoman, as described here: https://support.system76.com/articles/manage-repos-pop/

**Comment by zelfir** [comment]
Indeed, it's not related to the issue but it was just cancelling the apt update command. Anyway I figured out and managed to update to 455.28. I rebooted and tested with TESO again but unfortunately the problem is still there :(

**Comment by zelfir** [comment]
Well, it seems the issue was also linked to the shader cache used by the game.
Once Steam totally rebuild the shader cache with the new driver,  it solved the issue.

You can close this ticket :)

**Comment by leviport** [comment]
Glad to hear it, thanks for letting us know!

**Comment by Redbatman89** [comment]
So then the new driver works fine then?

**Comment by zelfir** [comment]
Yes
