### ISSUE TITLE
455: Vulkan Shader issues on Steam

### ISSUE THREAD

**Issue by Redbatman89** [pop-os/nvidia-graphics-drivers#66]
So a few hours ago I had downloaded the latest NVIDIA driver only after restart I noticed that the background processing of vulkan shaders was taking quite a long time. Rise of Tomb raider was taking almost 20mins so I rolled back to 440.100.

I don't know why it happened but now my shaders are fast again and are back to usual processing time. Please POP OS take another look at this driver, it's odd the driver was pushed out since it's a beta driver for the RTX 3000 series.

**Comment by Redbatman89** [comment]
> 
> 
> @NinjaTurtle007 could you elaborate on how it messed up your setup?
> 
> For what it's worth, the version mentioned in the title of this issue is no longer the current version. @Redbatman89 are you still having the issue on 455.28?

So I have had the driver 455.28 for a few days now and while I thought it was fixed completely, there are some issues still. While sharers seem to be okay again, some games such as Rise of Tomb raider take a long time to compile shaders. It took rise of tomb raider about 15 mins to compile shaders while the rest of my games are fast. And this is the native linux version 

Now while I only have to do this once steam launches its fine but if I have exit or update steam I have to do it all over again, which was fine when it only took five minutes. Other than that no other effects I have noticed.

**Comment by NinjaTurtle007** [comment]
@Redbatman89 have you tried with the open source driver? I'm getting tired of this nvidia non-sense.

**Comment by Redbatman89** [comment]
> 
> 
> @Redbatman89 have you tried with the open source driver? I'm getting tired of this nvidia non-sense.

No I haven't the open source driver performance is terrible. You get a fraction of the performance. I have a GTX 1080

**Comment by sasinduSilva** [comment]
Found this link on Youtube. Will be useful or fix your issue.
https://youtu.be/kixD-MyG0c4

**Comment by leviport** [comment]
This bug report appears to have gone stale, so I'm going to close it for now. Let me know if it's still a problem and I will reopen it.
