### ISSUE TITLE
Desktop craches /Relaunch when open OpenGL games

### ISSUE THREAD

**Issue by shagby** [pop-os/nvidia-graphics-drivers#82]
When upgrading to pop os 20.10 and playing for example x-plane

1 Opening x-plane
2 Desktop relaunch and both my screens flashes just like when you log in to the system 

From x.org1.log

[    14.063] (--) NVIDIA(GPU-0): CRT-0: disconnected
[    14.063] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    14.063] (--) NVIDIA(GPU-0): 
[    14.067] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    14.067] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    14.067] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    14.067] (--) NVIDIA(GPU-0): 
[    14.098] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[    14.098] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[    14.098] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[    14.098] (--) NVIDIA(GPU-0): 
[    14.098] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    14.098] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    14.098] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[    14.098] (--) NVIDIA(GPU-0): 
[    14.098] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    14.098] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    14.098] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    14.098] (--) NVIDIA(GPU-0): 
[    14.098] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[    14.098] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[    14.098] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[    14.098] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[    14.098] (--) NVIDIA(GPU-0): 
[    14.100] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    14.100] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    14.100] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    14.100] (--) NVIDIA(GPU-0): 
[    14.100] (--) NVIDIA(GPU-0): DFP-6: disconnected
[    14.100] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[    14.100] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[    14.100] (--) NVIDIA(GPU-0): 
[    14.100] (--) NVIDIA(GPU-0): DFP-7: disconnected
[    14.100] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[    14.100] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[    14.100] (--) NVIDIA(GPU-0): 
[    14.144] (II) NVIDIA(0): Setting mode "HDMI-0: nvidia-auto-select @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}, DP-2: 1920x1080_144 @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}"
[    14.303] (II) NVIDIA(0): Setting mode "HDMI-0: nvidia-auto-select @1920x1080 +1920+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}, DP-2: 1920x1080_144 @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}"
[    15.507] (--) NVIDIA(GPU-0): CRT-0: disconnected
[    15.507] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    15.507] (--) NVIDIA(GPU-0): 
[    15.511] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    15.511] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    15.511] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    15.511] (--) NVIDIA(GPU-0): 
[    15.541] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[    15.541] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[    15.541] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[    15.541] (--) NVIDIA(GPU-0): 
[    15.541] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    15.541] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    15.541] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[    15.542] (--) NVIDIA(GPU-0): 
[    15.542] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    15.542] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    15.542] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    15.542] (--) NVIDIA(GPU-0): 
[    15.542] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[    15.542] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[    15.542] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[    15.542] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[    15.542] (--) NVIDIA(GPU-0): 
[    15.543] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    15.543] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    15.543] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    15.543] (--) NVIDIA(GPU-0): 
[    15.543] (--) NVIDIA(GPU-0): DFP-6: disconnected
[    15.543] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[    15.543] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[    15.543] (--) NVIDIA(GPU-0): 
[    15.543] (--) NVIDIA(GPU-0): DFP-7: disconnected
[    15.543] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[    15.543] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[    15.543] (--) NVIDIA(GPU-0): 
[    16.031] (--) NVIDIA(GPU-0): CRT-0: disconnected
[    16.031] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    16.031] (--) NVIDIA(GPU-0): 
[    16.035] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    16.035] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    16.035] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    16.035] (--) NVIDIA(GPU-0): 
[    16.066] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[    16.066] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[    16.066] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[    16.066] (--) NVIDIA(GPU-0): 
[    16.066] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    16.066] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    16.066] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[    16.066] (--) NVIDIA(GPU-0): 
[    16.066] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    16.066] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    16.066] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    16.066] (--) NVIDIA(GPU-0): 
[    16.066] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[    16.066] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[    16.066] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[    16.066] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[    16.066] (--) NVIDIA(GPU-0): 
[    16.067] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    16.067] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    16.067] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    16.067] (--) NVIDIA(GPU-0): 
[    16.067] (--) NVIDIA(GPU-0): DFP-6: disconnected
[    16.067] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[    16.067] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[    16.067] (--) NVIDIA(GPU-0): 
[    16.067] (--) NVIDIA(GPU-0): DFP-7: disconnected
[    16.067] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[    16.067] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[    16.067] (--) NVIDIA(GPU-0): 
[    16.081] (--) NVIDIA(GPU-0): CRT-0: disconnected
[    16.081] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    16.081] (--) NVIDIA(GPU-0): 
[    16.084] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    16.084] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    16.084] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    16.084] (--) NVIDIA(GPU-0): 
[    16.115] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[    16.115] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[    16.115] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[    16.115] (--) NVIDIA(GPU-0): 
[    16.115] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    16.115] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    16.115] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[    16.115] (--) NVIDIA(GPU-0): 
[    16.115] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    16.115] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    16.115] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    16.115] (--) NVIDIA(GPU-0): 
[    16.116] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[    16.116] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[    16.116] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[    16.116] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[    16.116] (--) NVIDIA(GPU-0): 
[    16.117] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    16.117] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    16.117] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    16.117] (--) NVIDIA(GPU-0): 
[    16.117] (--) NVIDIA(GPU-0): DFP-6: disconnected
[    16.117] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[    16.117] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[    16.117] (--) NVIDIA(GPU-0): 
[    16.117] (--) NVIDIA(GPU-0): DFP-7: disconnected
[    16.117] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[    16.117] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[    16.117] (--) NVIDIA(GPU-0): 
[    16.128] (--) NVIDIA(GPU-0): CRT-0: disconnected
[    16.128] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[    16.128] (--) NVIDIA(GPU-0): 
[    16.132] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    16.132] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    16.132] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[    16.132] (--) NVIDIA(GPU-0): 
[    16.163] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[    16.163] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[    16.163] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[    16.163] (--) NVIDIA(GPU-0): 
[    16.163] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    16.163] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    16.163] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[    16.163] (--) NVIDIA(GPU-0): 
[    16.163] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    16.163] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    16.163] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    16.163] (--) NVIDIA(GPU-0): 
[    16.163] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[    16.163] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[    16.163] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[    16.163] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[    16.163] (--) NVIDIA(GPU-0): 
[    16.164] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    16.164] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    16.164] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    16.164] (--) NVIDIA(GPU-0): 
[    16.164] (--) NVIDIA(GPU-0): DFP-6: disconnected
[    16.164] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[    16.165] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[    16.165] (--) NVIDIA(GPU-0): 
[    16.165] (--) NVIDIA(GPU-0): DFP-7: disconnected
[    16.165] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[    16.165] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[    16.165] (--) NVIDIA(GPU-0): 
[   281.343] (--) NVIDIA(GPU-0): CRT-0: disconnected
[   281.343] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[   281.343] (--) NVIDIA(GPU-0): 
[   281.347] (--) NVIDIA(GPU-0): DFP-0: disconnected
[   281.347] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[   281.347] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[   281.347] (--) NVIDIA(GPU-0): 
[   281.377] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[   281.377] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[   281.377] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[   281.377] (--) NVIDIA(GPU-0): 
[   281.377] (--) NVIDIA(GPU-0): DFP-2: disconnected
[   281.377] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[   281.377] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[   281.377] (--) NVIDIA(GPU-0): 
[   281.378] (--) NVIDIA(GPU-0): DFP-3: disconnected
[   281.378] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[   281.378] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[   281.378] (--) NVIDIA(GPU-0): 
[   281.378] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[   281.378] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[   281.378] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[   281.378] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[   281.378] (--) NVIDIA(GPU-0): 
[   281.379] (--) NVIDIA(GPU-0): DFP-5: disconnected
[   281.379] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[   281.379] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[   281.379] (--) NVIDIA(GPU-0): 
[   281.379] (--) NVIDIA(GPU-0): DFP-6: disconnected
[   281.379] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[   281.379] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[   281.379] (--) NVIDIA(GPU-0): 
[   281.379] (--) NVIDIA(GPU-0): DFP-7: disconnected
[   281.379] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[   281.379] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[   281.379] (--) NVIDIA(GPU-0): 
[   281.383] (--) NVIDIA(GPU-0): CRT-0: disconnected
[   281.383] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[   281.383] (--) NVIDIA(GPU-0): 
[   281.387] (--) NVIDIA(GPU-0): DFP-0: disconnected
[   281.387] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[   281.387] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[   281.387] (--) NVIDIA(GPU-0): 
[   281.417] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): connected
[   281.417] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): Internal TMDS
[   281.417] (--) NVIDIA(GPU-0): Acer H235H (DFP-1): 600.0 MHz maximum pixel clock
[   281.417] (--) NVIDIA(GPU-0): 
[   281.417] (--) NVIDIA(GPU-0): DFP-2: disconnected
[   281.417] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[   281.417] (--) NVIDIA(GPU-0): DFP-2: 960.0 MHz maximum pixel clock
[   281.417] (--) NVIDIA(GPU-0): 
[   281.418] (--) NVIDIA(GPU-0): DFP-3: disconnected
[   281.418] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[   281.418] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[   281.418] (--) NVIDIA(GPU-0): 
[   281.418] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): connected
[   281.418] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): Internal DisplayPort
[   281.418] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): 960.0 MHz maximum pixel clock
[   281.418] (--) NVIDIA(GPU-0): Ancor Communications Inc VG248 (DFP-4): supports NVIDIA 3D Vision stereo.
[   281.418] (--) NVIDIA(GPU-0): 
[   281.419] (--) NVIDIA(GPU-0): DFP-5: disconnected
[   281.419] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[   281.419] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[   281.419] (--) NVIDIA(GPU-0): 
[   281.419] (--) NVIDIA(GPU-0): DFP-6: disconnected
[   281.419] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[   281.419] (--) NVIDIA(GPU-0): DFP-6: 960.0 MHz maximum pixel clock
[   281.419] (--) NVIDIA(GPU-0): 
[   281.419] (--) NVIDIA(GPU-0): DFP-7: disconnected
[   281.419] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[   281.419] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[   281.419] (--) NVIDIA(GPU-0):

**Comment by shagby** [comment]
[dmes.log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701192/dmes.log)
[gpu-manager.log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701193/gpu-manager.log)
[xorg.0.log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701194/xorg.0.log)
[xorg.1.log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701195/xorg.1.log)

**Comment by mmstick** [comment]
Needs gnome-shell logs from journalctl

**Comment by shagby** [comment]
[systemctl log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701840/systemctl.log)

**Comment by shagby** [comment]
Here seems to be the problem

Dec 16 10:45:03 pop-os gnome-shell[2460]: Error in freeze/thaw accounting
Dec 16 10:45:12 pop-os systemd[1796]: org.gnome.Shell@x11.service: Main process exited, code=dumped, status=5/TRAP
Dec 16 10:45:12 pop-os gsd-power[2666]: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient>
Dec 16 10:45:12 pop-os systemd[1796]: org.gnome.Shell@x11.service: Failed with result 'core-dump'.
Dec 16 10:45:12 pop-os systemd[1796]: org.gnome.Shell@x11.service: Scheduled restart job, restart counter is at 1.
Dec 16 10:45:12 pop-os systemd[1796]: Stopped GNOME Shell on X11.
Dec 16 10:45:12 pop-os systemd[1796]: Starting GNOME Shell on X11...

**Comment by shagby** [comment]
This only happens when upgrading to 20.10, in 20.04 everything is working perfectly!
I guess it has something to do with Gnome 3.38 ?!

**Comment by shagby** [comment]
When staring remmina, everything freezed and the desktop rebooted just like the game

[remmina.log](https://github.com/pop-os/nvidia-graphics-drivers/files/5701892/remmina.log)

**Comment by TechnologyMan101** [comment]
I think it has to do with GNOME 3.38 and not with the Pop!_OS NVIDIA drivers. This same issue is on Ubuntu. I have not encountered the issue on rolling release distros like Manjaro, probably because those are already on GNOME 3.38.2 while Pop!_OS and Ubuntu are still on 3.38.1. And I'm also using Intel Integrated Graphics, and I don't have any NVIDIA graphics cards installed. GNOME 3.38.2 has seemed to fix many problems when I was using Manjaro on my secondary drive.

**Comment by shagby** [comment]
But i have tried with Manjaro latest vers with gnome and it's the same issue there also.

**Comment by mmstick** [comment]
3.38.2 version of GNOME Shell is currently stuck not building in proposed. It will be released soon the moment it's built and working

**Comment by mmstick** [comment]
It's on its way out now

**Comment by shagby** [comment]
Is it released to pop OS 20.10? Now ? 

Br Staffan 

Skickat från min iPhone

**Comment by shagby** [comment]
Removed battery from motherboard and reinstalled my graphic card, the issues is now resolved!
